### ISSUE TITLE
Eccentricity - Infinite lengths

### ISSUE THREAD

**Issue by Simard302** [Pranavkhade/PACKMAN#34] opened 2022-05-27 15:34 UTC
When predicting hinges on the backbone, it sometimes fails due to infinite lengths. Is this caused by unconnected nodes? Can it be fixed by changing the alpha value? Should there be something in the code that handles this issue instead of crashing?

**Comment by Pranavkhade** [comment] 2022-05-28 01:06
Hello,

Thank you for posting the issue. Can you please provide the specifics of the parameters you gave? Also, did you use GUI, API, or CLI?

Yes, infinite length error can be caused by alpha values that are too low, which makes the graphs unconnected. Ideally, we recommend in the paper and on interfaces to start from alpha value 2.8. However, despite starting from 2.8, sometimes there are missing atoms in the structure that make the graph with unconnected nodes. 

Please give me the specifics, and I will try to pinpoint the problem and fix it.

Thanks,
Pranav

**Comment by Simard302** [comment] 2022-05-30 19:34
I tried using an Alpha value of 2.8 but the issue remains. Its less of an issue that the hinge can't be calculated, more an issue that the program crashes. Could there be a check for infinite path length instead of crashing?
Here is my PDB, and here is the code that causes the issue:
```python
from packman import molecule, predict_hinge

mol = molecule.load_structure("1crn_broken.pdb")
chains = mol[0].get_chains()
for chain in chains:
        backbone = [j for i in chain.get_backbone() for j in i if j is not None]
        predict_hinge(backbone, open("1crn_broken_hinges.txt", "w"), Alpha=2.8)
        hingeResidues = [j for i in chain.get_hinges() for j in i.get_elements()]
        print(hingeResidues)
```
Error:```
Traceback (most recent call last):
  File "hingetest.py", line 7, in <module>
    predict_hinge(backbone, open("1crn_broken_hinges.txt", "w"), Alpha=2.8)
  File "<...>\site-packages\packman\apps\predict_hinge.py", line 284, in predict_hinge
    centrality = eccentricity(ProteinGraph)
  File "<...>\site-packages\networkx\algorithms\distance_measures.py", line 264, in eccentricity
    raise nx.NetworkXError(msg)
networkx.exception.NetworkXError: Found infinite path length because the graph is not connected
```
[1crn_broken.zip](https://github.com/Pranavkhade/PACKMAN/files/8800493/1crn_broken.zip)

**Comment by Simard302** [comment] 2022-06-02 13:39
I would like to keep the same alpha value constant for all of my runs. Would it be possible to add a layer before the eccentricity is calculated that checks for any disconnected nodes in the network and omits them?

**Comment by Pranavkhade** [comment] 2022-06-02 17:09
I do not think that is a great idea because it is possible that there is a residue missing in the hinge region that disconnects the graph, and now since we see them as two disconnected graphs, we are trying to find a hinge inside the areas that would be considered as domains before the division.

I think increasing the alpha value is the best solution. I am not sure why you want to keep the alpha value exactly the same (if you can share it would be nice), but I think gradually increasing it shouldn't be a problem since the packing of protein is relative. Even the same protein, such as calmodulin in two different forms (1EXR and 1PRW), requires two different initial alpha values.

**Comment by Pranavkhade** [comment] 2022-06-06 20:27
Please let me know if you find the solution to increasing alpha value useful. I will close this issue on 06/15/2022 if the response is not received, assuming it is solved.

Thank you for reporting the issue.
Pranav

**Comment by Pranavkhade** [comment] 2022-06-09 00:03
Keep the alpha increment very low, and you will be fine.

Hinges can be different based on multiple factors, not just alpha value. However, we have seen that there is always overlap with the most prominent hinges. Lower alpha values show the most obvious hinges, and if you keep increasing the alpha value, you see less obvious hinges, as we have mentioned in the paper.

I will close this issue with this comment since the issue of the infinite length is solved and confirmed.

**Closed by Pranavkhade** 2022-06-09 00:03 UTC
